name: 2workflow
on: push

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: display Node Version on ubuntu
        run: node -v
  run-parralel-command:
    runs-on: windows-latest
    steps:
      - name: display Node Version on windows
        run: node -v
  run-second-command:
    runs-on: macos-latest
    needs: [run-first-command]
    steps:
      - name: display node version on mac
        run: node -v