name: 3workflow
on: push

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: ls -a 
      - name: copy files
        run: |
            git init
            git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
            git fetch origin
            git checkout main 
      - name: list files
        run: ls -a 