name: 5workflow
on: [push, issues, pull_request]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: event var
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      